USE [master]
GO

/****** Object:  Database [noel_felipe]    Script Date: 16/06/2020 23:39:21 ******/
CREATE DATABASE [noel_felipe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'noel_felipe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\noel_felipe.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'noel_felipe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\noel_felipe_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [noel_felipe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [noel_felipe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [noel_felipe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [noel_felipe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [noel_felipe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [noel_felipe] SET ARITHABORT OFF 
GO

ALTER DATABASE [noel_felipe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [noel_felipe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [noel_felipe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [noel_felipe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [noel_felipe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [noel_felipe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [noel_felipe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [noel_felipe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [noel_felipe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [noel_felipe] SET  DISABLE_BROKER 
GO

ALTER DATABASE [noel_felipe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [noel_felipe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [noel_felipe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [noel_felipe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [noel_felipe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [noel_felipe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [noel_felipe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [noel_felipe] SET RECOVERY FULL 
GO

ALTER DATABASE [noel_felipe] SET  MULTI_USER 
GO

ALTER DATABASE [noel_felipe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [noel_felipe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [noel_felipe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [noel_felipe] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [noel_felipe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [noel_felipe] SET QUERY_STORE = OFF
GO

ALTER DATABASE [noel_felipe] SET  READ_WRITE 
GO